### ISSUE TITLE
consider adding ISO3 country codes

### ISSUE THREAD

**Issue by fsolt** [fsolt/swiid#10]
Per Louis Chauvel via email:

> Thanks for the new version of swiid this october : this is very useful.
> I remain very skeptical about Stata command kountry:
> It is unable to recode names such as "Congo, R.D." () or
> "Czekoslovakia" (CSK)...
> OK I just have to clean the results, but if I face this difficulty, I
> guess hundreds of colleagues face the same...
> 
> This is precisely why the ISO3 string code could be the universal solution
> see
> https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
> https://en.wikipedia.org/wiki/ISO_3166-3
> 
> see the issues here in stata
> use "C:\Users\KARL\Documents\swiid6_1.dta" , clear
> replace country = "Cote D'Ivoire" if country == "CÃ´te D'Ivoire"
> kountry cou, from(other) stuck
> recode _I (.=0)
> ta country if _I==0, s(_I)
> 
> Thanks for all and take heart!
> Louis
>

**Comment by jackobailey** [comment]
You might find the countrycode package useful for doing the bulk of this work https://cran.r-project.org/web/packages/countrycode/countrycode.pdf

**Comment by fsolt** [comment]
Thanks, Jack, but I should have closed this one earlier: https://fsolt.org/swiid/swiid_faq/posts/how-to/country-codes.html
